let super_year_data ={
    bangkok: 
        [{"City":"Bangkok","Host_Since_Year":2009,"Superhost":"Regular Host","Id":2},
        {"City":"Bangkok","Host_Since_Year":2010,"Superhost":"Regular Host","Id":18},
        {"City":"Bangkok","Host_Since_Year":2010,"Superhost":"Super Host","Id":23},
        {"City":"Bangkok","Host_Since_Year":2011,"Superhost":"Regular Host","Id":40},
        {"City":"Bangkok","Host_Since_Year":2011,"Superhost":"Super Host","Id":32},
        {"City":"Bangkok","Host_Since_Year":2012,"Superhost":"Regular Host","Id":130},
        {"City":"Bangkok","Host_Since_Year":2012,"Superhost":"Super Host","Id":88},
        {"City":"Bangkok","Host_Since_Year":2013,"Superhost":"Regular Host","Id":321},
        {"City":"Bangkok","Host_Since_Year":2013,"Superhost":"Super Host","Id":122},
        {"City":"Bangkok","Host_Since_Year":2014,"Superhost":"Regular Host","Id":396},
        {"City":"Bangkok","Host_Since_Year":2014,"Superhost":"Super Host","Id":321},
        {"City":"Bangkok","Host_Since_Year":2015,"Superhost":"Regular Host","Id":948},
        {"City":"Bangkok","Host_Since_Year":2015,"Superhost":"Super Host","Id":429},
        {"City":"Bangkok","Host_Since_Year":2016,"Superhost":"Regular Host","Id":850},
        {"City":"Bangkok","Host_Since_Year":2016,"Superhost":"Super Host","Id":257},
        {"City":"Bangkok","Host_Since_Year":2017,"Superhost":"Regular Host","Id":675},
        {"City":"Bangkok","Host_Since_Year":2017,"Superhost":"Super Host","Id":182},
        {"City":"Bangkok","Host_Since_Year":2018,"Superhost":"Regular Host","Id":803},
        {"City":"Bangkok","Host_Since_Year":2018,"Superhost":"Super Host","Id":323},
        {"City":"Bangkok","Host_Since_Year":2019,"Superhost":"Regular Host","Id":643},
        {"City":"Bangkok","Host_Since_Year":2019,"Superhost":"Super Host","Id":335},
        {"City":"Bangkok","Host_Since_Year":2020,"Superhost":"Regular Host","Id":216},
        {"City":"Bangkok","Host_Since_Year":2020,"Superhost":"Super Host","Id":52},
        {"City":"Bangkok","Host_Since_Year":2021,"Superhost":"Regular Host","Id":40},
        {"City":"Bangkok","Host_Since_Year":2021,"Superhost":"Super Host","Id":78},
        {"City":"Bangkok","Host_Since_Year":2022,"Superhost":"Regular Host","Id":220},
        {"City":"Bangkok","Host_Since_Year":2022,"Superhost":"Super Host","Id":67}],

    hongkong:
    [
        { City: "Hong Kong", Host_Since_Year: 2010, Superhost: "Regular Host", Id: 15 },
        { City: "Hong Kong", Host_Since_Year: 2010, Superhost: "Super Host", Id: 1 },
        { City: "Hong Kong", Host_Since_Year: 2011, Superhost: "Regular Host", Id: 29 },
        { City: "Hong Kong", Host_Since_Year: 2011, Superhost: "Super Host", Id: 4 },
        { City: "Hong Kong", Host_Since_Year: 2012, Superhost: "Regular Host", Id: 62 },
        { City: "Hong Kong", Host_Since_Year: 2012, Superhost: "Super Host", Id: 10 },
        { City: "Hong Kong", Host_Since_Year: 2013, Superhost: "Regular Host", Id: 103 },
        { City: "Hong Kong", Host_Since_Year: 2013, Superhost: "Super Host", Id: 38 },
        { City: "Hong Kong", Host_Since_Year: 2014, Superhost: "Regular Host", Id: 137 },
        { City: "Hong Kong", Host_Since_Year: 2014, Superhost: "Super Host", Id: 28 },
        { City: "Hong Kong", Host_Since_Year: 2015, Superhost: "Regular Host", Id: 279 },
        { City: "Hong Kong", Host_Since_Year: 2015, Superhost: "Super Host", Id: 101 },
        { City: "Hong Kong", Host_Since_Year: 2016, Superhost: "Regular Host", Id: 251 },
        { City: "Hong Kong", Host_Since_Year: 2016, Superhost: "Super Host", Id: 24 },
        { City: "Hong Kong", Host_Since_Year: 2017, Superhost: "Regular Host", Id: 157 },
        { City: "Hong Kong", Host_Since_Year: 2017, Superhost: "Super Host", Id: 44 },
        { City: "Hong Kong", Host_Since_Year: 2018, Superhost: "Regular Host", Id: 110 },
        { City: "Hong Kong", Host_Since_Year: 2018, Superhost: "Super Host", Id: 18 },
        { City: "Hong Kong", Host_Since_Year: 2019, Superhost: "Regular Host", Id: 66 },
        { City: "Hong Kong", Host_Since_Year: 2019, Superhost: "Super Host", Id: 33 },
        { City: "Hong Kong", Host_Since_Year: 2020, Superhost: "Regular Host", Id: 20 },
        { City: "Hong Kong", Host_Since_Year: 2020, Superhost: "Super Host", Id: 7 },
        { City: "Hong Kong", Host_Since_Year: 2021, Superhost: "Regular Host", Id: 24 },
        { City: "Hong Kong", Host_Since_Year: 2021, Superhost: "Super Host", Id: 1 },
        { City: "Hong Kong", Host_Since_Year: 2022, Superhost: "Regular Host", Id: 46 },
        { City: "Hong Kong", Host_Since_Year: 2022, Superhost: "Super Host", Id: 3 },
      ],
      
    istanbul:
    [
        { City: "Istanbul", Host_Since_Year: 2009, Superhost: "Regular Host", Id: 1 },
        { City: "Istanbul", Host_Since_Year: 2010, Superhost: "Regular Host", Id: 33 },
        { City: "Istanbul", Host_Since_Year: 2010, Superhost: "Super Host", Id: 33 },
        { City: "Istanbul", Host_Since_Year: 2011, Superhost: "Regular Host", Id: 146 },
        { City: "Istanbul", Host_Since_Year: 2011, Superhost: "Super Host", Id: 88 },
        { City: "Istanbul", Host_Since_Year: 2012, Superhost: "Regular Host", Id: 295 },
        { City: "Istanbul", Host_Since_Year: 2012, Superhost: "Super Host", Id: 128 },
        { City: "Istanbul", Host_Since_Year: 2013, Superhost: "Regular Host", Id: 454 },
        { City: "Istanbul", Host_Since_Year: 2013, Superhost: "Super Host", Id: 285 },
        { City: "Istanbul", Host_Since_Year: 2014, Superhost: "Regular Host", Id: 1068 },
        { City: "Istanbul", Host_Since_Year: 2014, Superhost: "Super Host", Id: 385 },
        { City: "Istanbul", Host_Since_Year: 2015, Superhost: "Regular Host", Id: 982 },
        { City: "Istanbul", Host_Since_Year: 2015, Superhost: "Super Host", Id: 466 },
        { City: "Istanbul", Host_Since_Year: 2016, Superhost: "Regular Host", Id: 902 },
        { City: "Istanbul", Host_Since_Year: 2016, Superhost: "Super Host", Id: 479 },
        { City: "Istanbul", Host_Since_Year: 2017, Superhost: "Regular Host", Id: 730 },
        { City: "Istanbul", Host_Since_Year: 2017, Superhost: "Super Host", Id: 303 },
        { City: "Istanbul", Host_Since_Year: 2018, Superhost: "Regular Host", Id: 1320 },
        { City: "Istanbul", Host_Since_Year: 2018, Superhost: "Super Host", Id: 422 },
        { City: "Istanbul", Host_Since_Year: 2019, Superhost: "Regular Host", Id: 1722 },
        { City: "Istanbul", Host_Since_Year: 2019, Superhost: "Super Host", Id: 616 },
        { City: "Istanbul", Host_Since_Year: 2020, Superhost: "Regular Host", Id: 1444 },
        { City: "Istanbul", Host_Since_Year: 2020, Superhost: "Super Host", Id: 363 },
        { City: "Istanbul", Host_Since_Year: 2021, Superhost: "Regular Host", Id: 1832 },
        { City: "Istanbul", Host_Since_Year: 2021, Superhost: "Super Host", Id: 614 },
        { City: "Istanbul", Host_Since_Year: 2022, Superhost: "Regular Host", Id: 3288 },
        { City: "Istanbul", Host_Since_Year: 2022, Superhost: "Super Host", Id: 617 },
      ],
      
    london:
    [
        { City: "London", Host_Since_Year: 2008, Superhost: "Regular Host", Id: 2 },
        { City: "London", Host_Since_Year: 2008, Superhost: "Super Host", Id: 7 },
        { City: "London", Host_Since_Year: 2009, Superhost: "Regular Host", Id: 43 },
        { City: "London", Host_Since_Year: 2009, Superhost: "Super Host", Id: 6 },
        { City: "London", Host_Since_Year: 2010, Superhost: "Regular Host", Id: 98 },
        { City: "London", Host_Since_Year: 2010, Superhost: "Super Host", Id: 74 },
        { City: "London", Host_Since_Year: 2011, Superhost: "Regular Host", Id: 754 },
        { City: "London", Host_Since_Year: 2011, Superhost: "Super Host", Id: 287 },
        { City: "London", Host_Since_Year: 2012, Superhost: "Regular Host", Id: 1509 },
        { City: "London", Host_Since_Year: 2012, Superhost: "Super Host", Id: 804 },
        { City: "London", Host_Since_Year: 2013, Superhost: "Regular Host", Id: 1798 },
        { City: "London", Host_Since_Year: 2013, Superhost: "Super Host", Id: 736 },
        { City: "London", Host_Since_Year: 2014, Superhost: "Regular Host", Id: 2825 },
        { City: "London", Host_Since_Year: 2014, Superhost: "Super Host", Id: 1136 },
        { City: "London", Host_Since_Year: 2015, Superhost: "Regular Host", Id: 3877 },
        { City: "London", Host_Since_Year: 2015, Superhost: "Super Host", Id: 1254 },
        { City: "London", Host_Since_Year: 2016, Superhost: "Regular Host", Id: 3051 },
        { City: "London", Host_Since_Year: 2016, Superhost: "Super Host", Id: 1027 },
        { City: "London", Host_Since_Year: 2017, Superhost: "Regular Host", Id: 2310 },
        { City: "London", Host_Since_Year: 2017, Superhost: "Super Host", Id: 569 },
        { City: "London", Host_Since_Year: 2018, Superhost: "Regular Host", Id: 2019 },
        { City: "London", Host_Since_Year: 2018, Superhost: "Super Host", Id: 646 },
        { City: "London", Host_Since_Year: 2019, Superhost: "Regular Host", Id: 2256 },
        { City: "London", Host_Since_Year: 2019, Superhost: "Super Host", Id: 421 },
        { City: "London", Host_Since_Year: 2020, Superhost: "Regular Host", Id: 1097 },
        { City: "London", Host_Since_Year: 2020, Superhost: "Super Host", Id: 258 },
        { City: "London", Host_Since_Year: 2021, Superhost: "Regular Host", Id: 1305 },
        { City: "London", Host_Since_Year: 2021, Superhost: "Super Host", Id: 390 },
        { City: "London", Host_Since_Year: 2022, Superhost: "Regular Host", Id: 2635 },
        { City: "London", Host_Since_Year: 2022, Superhost: "Super Host", Id: 362 },
      ],
      
    newyork:
    [
        { City: "New York City", Host_Since_Year: 2008, Superhost: "Regular Host", Id: 8 },
        { City: "New York City", Host_Since_Year: 2008, Superhost: "Super Host", Id: 3 },
        { City: "New York City", Host_Since_Year: 2009, Superhost: "Regular Host", Id: 82 },
        { City: "New York City", Host_Since_Year: 2009, Superhost: "Super Host", Id: 41 },
        { City: "New York City", Host_Since_Year: 2010, Superhost: "Regular Host", Id: 179 },
        { City: "New York City", Host_Since_Year: 2010, Superhost: "Super Host", Id: 142 },
        { City: "New York City", Host_Since_Year: 2011, Superhost: "Regular Host", Id: 429 },
        { City: "New York City", Host_Since_Year: 2011, Superhost: "Super Host", Id: 344 },
        { City: "New York City", Host_Since_Year: 2012, Superhost: "Regular Host", Id: 759 },
        { City: "New York City", Host_Since_Year: 2012, Superhost: "Super Host", Id: 516 },
        { City: "New York City", Host_Since_Year: 2013, Superhost: "Regular Host", Id: 901 },
        { City: "New York City", Host_Since_Year: 2013, Superhost: "Super Host", Id: 569 },
        { City: "New York City", Host_Since_Year: 2014, Superhost: "Regular Host", Id: 1226 },
        { City: "New York City", Host_Since_Year: 2014, Superhost: "Super Host", Id: 652 },
        { City: "New York City", Host_Since_Year: 2015, Superhost: "Regular Host", Id: 1333 },
        { City: "New York City", Host_Since_Year: 2015, Superhost: "Super Host", Id: 734 },
        { City: "New York City", Host_Since_Year: 2016, Superhost: "Regular Host", Id: 1247 },
        { City: "New York City", Host_Since_Year: 2016, Superhost: "Super Host", Id: 761 },
        { City: "New York City", Host_Since_Year: 2017, Superhost: "Regular Host", Id: 991 },
        { City: "New York City", Host_Since_Year: 2017, Superhost: "Super Host", Id: 834 },
        { City: "New York City", Host_Since_Year: 2018, Superhost: "Regular Host", Id: 1063 },
        { City: "New York City", Host_Since_Year: 2018, Superhost: "Super Host", Id: 548 },
        { City: "New York City", Host_Since_Year: 2019, Superhost: "Regular Host", Id: 1090 },
        { City: "New York City", Host_Since_Year: 2019, Superhost: "Super Host", Id: 543 },
        { City: "New York City", Host_Since_Year: 2020, Superhost: "Regular Host", Id: 664 },
        { City: "New York City", Host_Since_Year: 2020, Superhost: "Super Host", Id: 415 },
        { City: "New York City", Host_Since_Year: 2021, Superhost: "Regular Host", Id: 1166 },
        { City: "New York City", Host_Since_Year: 2021, Superhost: "Super Host", Id: 608 },
        { City: "New York City", Host_Since_Year: 2022, Superhost: "Regular Host", Id: 1291 },
        { City: "New York City", Host_Since_Year: 2022, Superhost: "Super Host", Id: 362 },
      ],
      
    paris:
    [
        { City: "Paris", Host_Since_Year: 2008, Superhost: "Regular Host", Id: 1 },
        { City: "Paris", Host_Since_Year: 2008, Superhost: "Super Host", Id: 1 },
        { City: "Paris", Host_Since_Year: 2009, Superhost: "Regular Host", Id: 17 },
        { City: "Paris", Host_Since_Year: 2009, Superhost: "Super Host", Id: 46 },
        { City: "Paris", Host_Since_Year: 2010, Superhost: "Regular Host", Id: 133 },
        { City: "Paris", Host_Since_Year: 2010, Superhost: "Super Host", Id: 53 },
        { City: "Paris", Host_Since_Year: 2011, Superhost: "Regular Host", Id: 334 },
        { City: "Paris", Host_Since_Year: 2011, Superhost: "Super Host", Id: 166 },
        { City: "Paris", Host_Since_Year: 2012, Superhost: "Regular Host", Id: 1066 },
        { City: "Paris", Host_Since_Year: 2012, Superhost: "Super Host", Id: 500 },
        { City: "Paris", Host_Since_Year: 2013, Superhost: "Regular Host", Id: 1917 },
        { City: "Paris", Host_Since_Year: 2013, Superhost: "Super Host", Id: 821 },
        { City: "Paris", Host_Since_Year: 2014, Superhost: "Regular Host", Id: 2150 },
        { City: "Paris", Host_Since_Year: 2014, Superhost: "Super Host", Id: 933 },
        { City: "Paris", Host_Since_Year: 2015, Superhost: "Regular Host", Id: 2531 },
        { City: "Paris", Host_Since_Year: 2015, Superhost: "Super Host", Id: 835 },
        { City: "Paris", Host_Since_Year: 2016, Superhost: "Regular Host", Id: 1845 },
        { City: "Paris", Host_Since_Year: 2016, Superhost: "Super Host", Id: 682 },
        { City: "Paris", Host_Since_Year: 2017, Superhost: "Regular Host", Id: 981 },
        { City: "Paris", Host_Since_Year: 2017, Superhost: "Super Host", Id: 305 },
        { City: "Paris", Host_Since_Year: 2018, Superhost: "Regular Host", Id: 932 },
        { City: "Paris", Host_Since_Year: 2018, Superhost: "Super Host", Id: 368 },
        { City: "Paris", Host_Since_Year: 2019, Superhost: "Regular Host", Id: 1118 },
        { City: "Paris", Host_Since_Year: 2019, Superhost: "Super Host", Id: 383 },
        { City: "Paris", Host_Since_Year: 2020, Superhost: "Regular Host", Id: 681 },
        { City: "Paris", Host_Since_Year: 2020, Superhost: "Super Host", Id: 147 },
        { City: "Paris", Host_Since_Year: 2021, Superhost: "Regular Host", Id: 740 },
        { City: "Paris", Host_Since_Year: 2021, Superhost: "Super Host", Id: 194 },
        { City: "Paris", Host_Since_Year: 2022, Superhost: "Regular Host", Id: 1484 },
        { City: "Paris", Host_Since_Year: 2022, Superhost: "Super Host", Id: 227 },
      ],

    singapore:
    [
        { City: "Singapore", Host_Since_Year: 2009, Superhost: "Regular Host", Id: 1 },
        { City: "Singapore", Host_Since_Year: 2010, Superhost: "Regular Host", Id: 3 },
        { City: "Singapore", Host_Since_Year: 2011, Superhost: "Regular Host", Id: 49 },
        { City: "Singapore", Host_Since_Year: 2012, Superhost: "Regular Host", Id: 89 },
        { City: "Singapore", Host_Since_Year: 2012, Superhost: "Super Host", Id: 3 },
        { City: "Singapore", Host_Since_Year: 2013, Superhost: "Regular Host", Id: 104 },
        { City: "Singapore", Host_Since_Year: 2013, Superhost: "Super Host", Id: 6 },
        { City: "Singapore", Host_Since_Year: 2014, Superhost: "Regular Host", Id: 84 },
        { City: "Singapore", Host_Since_Year: 2014, Superhost: "Super Host", Id: 24 },
        { City: "Singapore", Host_Since_Year: 2015, Superhost: "Regular Host", Id: 105 },
        { City: "Singapore", Host_Since_Year: 2015, Superhost: "Super Host", Id: 19 },
        { City: "Singapore", Host_Since_Year: 2016, Superhost: "Regular Host", Id: 177 },
        { City: "Singapore", Host_Since_Year: 2016, Superhost: "Super Host", Id: 44 },
        { City: "Singapore", Host_Since_Year: 2017, Superhost: "Regular Host", Id: 132 },
        { City: "Singapore", Host_Since_Year: 2017, Superhost: "Super Host", Id: 12 },
        { City: "Singapore", Host_Since_Year: 2018, Superhost: "Regular Host", Id: 46 },
        { City: "Singapore", Host_Since_Year: 2018, Superhost: "Super Host", Id: 21 },
        { City: "Singapore", Host_Since_Year: 2019, Superhost: "Regular Host", Id: 54 },
        { City: "Singapore", Host_Since_Year: 2019, Superhost: "Super Host", Id: 1 },
        { City: "Singapore", Host_Since_Year: 2020, Superhost: "Regular Host", Id: 25 },
        { City: "Singapore", Host_Since_Year: 2020, Superhost: "Super Host", Id: 32 },
        { City: "Singapore", Host_Since_Year: 2021, Superhost: "Regular Host", Id: 10 },
        { City: "Singapore", Host_Since_Year: 2021, Superhost: "Super Host", Id: 3 },
        { City: "Singapore", Host_Since_Year: 2022, Superhost: "Regular Host", Id: 77 },
        { City: "Singapore", Host_Since_Year: 2022, Superhost: "Super Host", Id: 8 },
      ]
};